{% set name = "libwebsockets" %}
{% set version = "4.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/warmcat/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c2ae635485b8ef8d383dee0aee29ad6272d4462e527d29d9af014ab4a2465cbd

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - pkg-config
  host:
    - libuv
    - openssl
  run:
    - openssl
    - libuv

test:
  commands:
    - test -d ${PREFIX}/include/libwebsockets
    - test -e ${PREFIX}/lib/libwebsockets.so

about:
  home: https://libwebsockets.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: canonical libwebsockets.org websocket library

  description: |
    Libwebsockets is a simple-to-use, pure C library providing client and server
    for **http/1**, **http/2**, **websockets** and other protocols in a security-minded,
    lightweight, configurable, scalable and flexible way.  It's easy to build and
    cross-build via cmake and is suitable for tasks from embedded RTOS through mass
    cloud serving.
  dev_url: https://github.com/warmcat/libwebsockets
  doc_url: https://libwebsockets.org/lws-api-doc-master/html/index.html

extra:
  recipe-maintainers:
    - sodre
