travis:
  secure:
    BINSTAR_TOKEN: o4CK2hp+lla8y0PQPrwBOvlgbUDhyMU8BUJ38aSYE6KRlSWcJmMBrwryl+KlIHaTMg6DZa/ZXGUDjY+/tKhG0v3rHMQL31+mh2OLUZ1XWu+c+XiPFOngUaZoVCCaa1QyYg7p62uJNS90zLljMGFssw/w9Z2gBDpjHAXTSPlqpjzBVF0NzL0Hbz+j1CXp2/Qnh408U5YbXkjiHDWg0BcyUerlKE8lCxl3BNJWMtycEN1sJi4atGhTAtVZVqPZLcAHUXgAegWCVaehsfO2m8f19o2/Ck00J7sVTuryTNHF0PFlRtd1ucfIWjQKeFTGU00FFxVgeSrmoLVRo9bTNznBApt7ArUTOeLc4lVZqKih+lErgYT4iUhu0bA6Rh9Hj6LTVeeuTKx3U7MMlIbIAbEnJRUdOTo8acX5FqP762JDGu0clTktdMaQgNEEqgqyc1JWV5gpTpQX26Z6SbZ2na0IkaDQ2Y+aRplpPWPw8hipfMTAg56fVPpavarax8aK72syD3hChTp8PoDCgVagAPsbOVegHI9tI/es4N09LKPTPMzhXEMJRCaoC4rwch9PTD4XMPVTONvu3XMaqEcw/nYyvjHJrncP/LyB5gubviKw/xluuqy8wCXJ9V5FMewLAjHPa+8voCqgV4+4YTKIpzar28b64DVzXO+iXsSnuLPyfIQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
